### ISSUE TITLE
Unused interfaces cause a compilation error

### ISSUE THREAD

**Issue by schuma7** [graphql-nexus/schema#111] opened 2019-04-14 15:39 UTC
Hi,

I'm currently in the process of migrating my codebase to Nexus. I can successfully run the following code snippet using `ts-node-dev --no-notify --transpileOnly --respawn src/server.ts`:
```javascript
import { asNexusMethod, interfaceType, queryField } from 'nexus';
import { GraphQLDate } from 'graphql-iso-date';

const DateScalar = asNexusMethod(GraphQLDate, 'date');

const DisplayableError = interfaceType({
  name: 'DisplayableError',
  definition(t) {
    t.list.string('field', { nullable: true });
    t.string('logCode', { nullable: true });
    t.string('message');
    t.resolveType(() => undefined);
  },
});

const Node = interfaceType({
  name: 'Node',
  definition(t) {
    t.id('id');
    t.resolveType(() => undefined);
  },
});

const currentDateQueryField = queryField('currentDate', {
  type: DateScalar,
  resolve() {
    return new Date();
  },
});

export { DateScalar, DisplayableError, Node, currentDateQueryField };

```
However, when trying to compile it using _tsc_ I get the following errors:

```
node_modules/nexus/dist/builder.d.ts:203:6 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

203   ): GraphQLObjectType<
         ~~~~~~~~~~~~~~~~~~
204     any,
    ~~~~~~~~
...
208     }
    ~~~~~
209   >;
    ~~~

node_modules/nexus/dist/builder.d.ts:227:6 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

227   ): GraphQLObjectType<
         ~~~~~~~~~~~~~~~~~~
228     any,
    ~~~~~~~~
...
232     }
    ~~~~~
233   >[];
    ~~~

node_modules/nexus/dist/utils.d.ts:15:9 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

 15   type: GraphQLObjectType<
            ~~~~~~~~~~~~~~~~~~
 16     any,
    ~~~~~~~~
...
 20     }
    ~~~~~
 21   >,
    ~~~

src/common/commonSchema2.ts:11:5 - error TS2345: Argument of type '[]' is not assignable to parameter of type '[OutputScalarConfig<"DisplayableError", "message"> & { resolve: FieldResolver<"DisplayableError", "message">; }] | [FieldResolver<"DisplayableError", "message">]'.
  Type '[]' is not assignable to type '[FieldResolver<"DisplayableError", "message">]'.
    Property '0' is missing in type '[]'.

11     t.string('message');
       ~~~~~~~~~~~~~~~~~~~

src/common/commonSchema2.ts:19:5 - error TS2345: Argument of type '[]' is not assignable to parameter of type '[OutputScalarConfig<"Node", "id"> & { resolve: FieldResolver<"Node", "id">; }] | [FieldResolver<"Node", "id">]'.
  Type '[]' is not assignable to type '[FieldResolver<"Node", "id">]'.
    Property '0' is missing in type '[]'.

19     t.id('id');
       ~~~~~~~~~~

src/common/commonSchema2.ts:24:57 - error TS2345: Argument of type '{ type: GraphQLScalarType; resolve(): Date; }' is not assignable to parameter of type 'NexusOutputFieldConfig<"Query", "currentDate"> | (() => NexusOutputFieldConfig<"Query", "currentDate">)'.
  Type '{ type: GraphQLScalarType; resolve(): Date; }' is not assignable to type '() => NexusOutputFieldConfig<"Query", "currentDate">'.
    Type '{ type: GraphQLScalarType; resolve(): Date; }' provides no match for the signature '(): NexusOutputFieldConfig<"Query", "currentDate">'.

 24 const currentDateQueryField = queryField('currentDate', {
                                                            ~
 25   type: DateScalar,
    ~~~~~~~~~~~~~~~~~~~
...
 28   },
    ~~~~
 29 });
```
I'm using Node v10.5.0 and my package deps look as follows:
```
"dependencies": {
   "@okgrow/graphql-scalars": "^0.4.5",
    "apollo-datasource-rest": "^0.3.2",
    "apollo-server": "^2.3.1",
    "apollo-server-express": "^2.3.1",
    "config": "^3.0.1",
    "express": "^4.16.4",
    "graphql": "^14.1.1",
    "graphql-iso-date": "^3.6.1",
    "graphql-tools": "^4.0.4",
    "graphql-type-json": "^0.2.1",
    "jsonwebtoken": "^8.5.0",
    "moment": "^2.24.0",
    "nexus": "^0.11.6",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/config": "0.0.34",
    "@types/graphql-iso-date": "^3.3.1",
    "@types/graphql-type-json": "^0.1.3",
    "@types/jsonwebtoken": "^8.3.2",
    "@types/uuid": "^3.4.4",
    "@typescript-eslint/eslint-plugin": "^1.2.0",
    "@typescript-eslint/eslint-plugin-tslint": "^1.3.0",
    "@typescript-eslint/parser": "^1.3.0",
    "cross-env": "^5.2.0",
    "eslint": "^5.13.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^4.0.0",
    "eslint-import-resolver-typescript": "^1.1.1",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-prettier": "^3.0.1",
    "prettier": "1.16.4",
    "rimraf": "^2.6.3",
    "ts-node-dev": "^1.0.0-pre.32",
    "tslint": "^5.12.1",
    "typescript": "^3.1.3"
  }
```
I'd appreciate if someone could provide some pointers as to what what might be the issue here.

**Comment by schuma7** [comment] 2019-04-15 09:38
I managed to get it to compile by:

1. changing `type: DateScalar` of the currentDateQueryField to `type: 'Date'`

2. making sure the Node interface is actually implemented by an object type that is used on the Root query

Is it expected behaviour that interfaces that are defined but not implemented anywhere cause the compilation step to fail? The error message that the Typescript compiler produces in that case is rather cryptic at the moment.

**Comment by tgriesser** [comment] 2019-04-15 16:40
> The error message that the Typescript compiler produces in that case is rather cryptic at the moment.

Yeah that's a frustration of TypeScript generally speaking, especially with how we're doing the conditionals. Hoping they make some improvements on that in the future.

> Is it expected behaviour that interfaces that are defined but not implemented anywhere cause the compilation step to fail?

No, this is a bug.

**Comment by schuma7** [comment] 2019-04-15 19:19
Thanks for clarifying, let's hope TypeScript finds a way to improve their error output soon.

**Comment by saostad** [comment] 2019-09-04 18:19
I fixed it by adding a resolver to field definition:
```
t.id("id", { resolve: () => "" });
``` 
is it a correct way of doing it?

**Comment by Ericnr** [comment] 2019-10-04 17:41
Having the same problem. Writing the resolver fixed but I really dont want to have to write a resolver for every field. One thing that also fixed it was turning `strickNullChecks` to false in TSconfig, which also isn't nice :/

**Comment by mdrafee03** [comment] 2020-06-13 00:13
graphql downgrade to 14.6. It solved my problem.

**Comment by arnaud-zg** [comment] 2020-06-17 22:28
> graphql downgrade to 14.6. It solved my problem.

I also have the same issue, thanks for the tips, by the way do you know why it's not compatible with `graphql@15`?

**Comment by georgekrax** [comment] 2020-06-29 14:16
It works just fine for me with `graphql@15.0.0`.

**Comment by arnaud-zg** [comment] 2020-06-29 20:47
I just checked on my side my issue come from the front-end side, I use `apollo-client` as graphql client. For the moment it's not yet compatible with `graphql@15`. A pull request has been merged 4 days ago, I think it will be available soon. 😺

**Comment by arnaud-zg** [comment] 2020-06-29 20:51
Don't you have these errors just below on this file `node_modules/@nexus/schema/dist/builder.d.ts`? :thinking: 
![image](https://user-images.githubusercontent.com/10991546/86054642-d0230380-ba5a-11ea-83c1-af2ef23bd6a1.png)

**Comment by georgekrax** [comment] 2020-06-30 12:49
Nope, you can also download & use `graphql@14.6.0`, which I find personally as the most stable version of **GraphQL** during these days.

**Comment by MarvinRudolph** [comment] 2020-07-14 08:21
Same problem, works with `graphql@14.6.0` but not with `15.0.0` (or `15.3.0`). Any chance to resolve this?

**Comment by georgekrax** [comment] 2020-07-15 09:17
I think everyone should choose what works best for themselves. Just try and expirement and then decide on what you like and not throws you any error.

**Comment by VijayManchi** [comment] 2020-09-01 05:06
Yup no luck with 15.0.0 or 15.3.0 yet. Using 14.6.0 to workaround.

**Comment by imjakechapman** [comment] 2020-09-20 17:09
Any updates on this issue? Was running 15.3.0 and had to downgrade to 14.6.0 to no longer get errors on compilation.

**Comment by jasonkuhrt** [comment] 2020-10-20 17:40
Unable to reproduce with `0.17.0-next.3`. If someone can, please post a repro we can look at.

**Closed by jasonkuhrt** 2020-10-20 17:40 UTC
Labels: type/bug
