### ISSUE TITLE
Typings are broken

### ISSUE THREAD

**Issue by cyrus-za** [graphql-nexus/schema#480] opened 2020-08-06 08:03 UTC
Types are broken in `@nexus/schema/dist/definitions/subscriptionType.d.ts` 

Posting screenshot as it is easier to read
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/1845861/89506729-d6c83780-d7cb-11ea-9dfa-49582b2b14e8.png">

Posting text so google can find this issue when others expeirence the same

```sh
node_modules/@nexus/schema/dist/definitions/subscriptionType.d.ts:31:9 - error TS2416: Property 'list' in type 'SubscriptionDefinitionBlock' is not assignable to the same property in base type 'ObjectDefinitionBlock<"Subscription">'.
  Type 'SubscriptionDefinitionBlock' is not assignable to type 'OutputDefinitionBlock<"Subscription">'.
    Types of property 'field' are incompatible.
      Type '<FieldName extends string>(name: FieldName, fieldConfig: SubscribeFieldConfig<"Subscription", FieldName, any>) => void' is not assignable to type '<FieldName extends string>(name: FieldName, fieldConfig: FieldOutConfig<"Subscription", FieldName>) => void'.
        Types of parameters 'fieldConfig' and 'fieldConfig' are incompatible.
          Type 'FieldOutConfig<"Subscription", FieldName>' is not assignable to type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.
            Type '(NexusOutputFieldConfig<"Subscription", FieldName> & { resolve: FieldResolver<"Subscription", FieldName>; }) | NexusOutputFieldConfig<"Subscription", FieldName>' is not assignable to type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.
              Property 'subscribe' is missing in type 'NexusOutputFieldConfig<"Subscription", FieldName> & { resolve: FieldResolver<"Subscription", FieldName>; }' but required in type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.

31     get list(): SubscriptionDefinitionBlock;
           ~~~~

  node_modules/@nexus/schema/dist/definitions/subscriptionType.d.ts:23:5
    23     subscribe(root: object, args: ArgsValue<TypeName, FieldName>, ctx: GetGen<'context'>, info: GraphQLResolveInfo): MaybePromise<AsyncIterator<T>> | MaybePromiseDeep<AsyncIterator<T>>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'subscribe' is declared here.

node_modules/@nexus/schema/dist/definitions/subscriptionType.d.ts:37:5 - error TS2416: Property 'field' in type 'SubscriptionDefinitionBlock' is not assignable to the same property in base type 'ObjectDefinitionBlock<"Subscription">'.
  Type '<FieldName extends string>(name: FieldName, fieldConfig: SubscribeFieldConfig<"Subscription", FieldName, any>) => void' is not assignable to type '<FieldName extends string>(name: FieldName, fieldConfig: FieldOutConfig<"Subscription", FieldName>) => void'.
    Types of parameters 'fieldConfig' and 'fieldConfig' are incompatible.
      Type 'FieldOutConfig<"Subscription", FieldName>' is not assignable to type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.
        Type '(NexusOutputFieldConfig<"Subscription", FieldName> & { resolve: FieldResolver<"Subscription", FieldName>; }) | NexusOutputFieldConfig<"Subscription", FieldName>' is not assignable to type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.
          Property 'subscribe' is missing in type 'NexusOutputFieldConfig<"Subscription", FieldName> & { resolve: FieldResolver<"Subscription", FieldName>; }' but required in type 'SubscribeFieldConfig<"Subscription", FieldName, any>'.

37     field<FieldName extends string>(name: FieldName, fieldConfig: SubscribeFieldConfig<'Subscription', FieldName>): void;
       ~~~~~

  node_modules/@nexus/schema/dist/definitions/subscriptionType.d.ts:23:5
    23     subscribe(root: object, args: ArgsValue<TypeName, FieldName>, ctx: GetGen<'context'>, info: GraphQLResolveInfo): MaybePromise<AsyncIterator<T>> | MaybePromiseDeep<AsyncIterator<T>>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'subscribe' is declared here.
```

**Comment by alexvilchis** [comment] 2020-08-06 18:08
I have the same issue

**Comment by cyrus-za** [comment] 2020-08-07 07:29
I can confirm that downgrading to `@nexus/schema@0.14.0` fixes the isusue

**Comment by jasonkuhrt** [comment] 2020-08-07 13:17
@cyrus-za are you using `subscriptionType` nexus type builder?

**Comment by Sytten** [comment] 2020-08-07 14:25
Maybe this is due to changes we made in the MaybePromiseDeep?

**Comment by tgriesser** [comment] 2020-08-18 19:12
Just hit this as well, looks to be due to the changes in https://github.com/graphql-nexus/schema/pull/462 - can reproduce by installing the latest `@nexus/schema` and `"skipLibCheck": false`.

I think might have been why I punted on adding a dedicated `subscriptionType` builder in the first place. It can't easily implement `ObjectDefinitionBlock` because this implements `OutputDefinitionBlock` which includes any of the JIT "plugin" fields added to the builder, which are going to have different config signatures.

I suppose you may be able to make this work by running both conditionals for the `ScalarSubSpread` and `SubscribeFieldConfig` through the `ScalarOutSpread` and `FieldOutConfig` with a ternary - that way the configs would be the same structurally for both class methods.

**Comment by cyrus-za** [comment] 2020-08-18 21:58
Sorry for the delay @jasonkuhrt but no I am not using subscriptionType

**Comment by jasonkuhrt** [comment] 2020-08-19 13:14
Thanks @cyrus-za for confirming. I'm less sure about what is going on then though.

@tgriesser Yeah didn't feel as simple as I expected once getting into it. Looks like we still have some work to do! We'll try to look into this soon, even more so if it's affecting non-subscription-type users.

On vacation, back next week. Chance we can start then but not sure.

**Comment by jasonkuhrt** [comment] 2020-10-20 15:15
Fixed by #564

**Closed by jasonkuhrt** 2020-10-20 15:15 UTC
Labels: Types, type/bug

**Comment by cyrus-za** [comment] 2020-10-21 12:24
Thanks for fixing @jasonkuhrt. I want to add that I have a prisma model that is called a Subscription (references a stripe subscription and was created long before the project even used gql or prisma). I am not sure if its related to this, but for some reason when theres a `objectType({ name: 'Subscription' })` Graphql playground shows a gql subscriptions in the docs, despite no apollo subscriptions even turned on

**Comment by jasonkuhrt** [comment] 2020-10-21 12:39
@cyrus-za Interesting, sounds like an issue, feel free to create a new one!
