### ISSUE TITLE
resolver args type as any rather than generated type

### ISSUE THREAD

**Issue by otrebu** [graphql-nexus/schema#418] opened 2020-04-23 17:23 UTC
```
const Query2 = extendType({
  type: 'Query',
  definition(t) {
    t.string('hello', {
      args: { name: stringArg({ nullable: true }) },
      resolve: (parent, args) {

      },
    });
  },
});
```

I have had this issue many times, I am not sure if I am missing something or it is a bug.

The resolve type is not mapped correctly. Both parent and root are of type any.

**Comment by FedericoBiccheddu** [comment] 2020-05-23 10:02
I'm having the same issue, but using `queryField`:
```typescript
import {makeSchema, queryField, stringArg, objectType} from "@nexus/schema"

const User = objectType({
  name: "User",
  definition(t) {
    t.string("nickname")
  },
})

const UserQuery = queryField("user", {
  type: User,
  args: {
    id: stringArg({required: true}),
  },
  resolve: (_, args) => ({
    nickname: "...",
  }),
})

export default makeSchema({
  types: {
    User,
    UserQuery,
  },
  outputs: false,
})
```

I expect the `resolve` signature to be typed, having the second parameter, `args`, as `args: { id: string }` or something like that.

Even with the typegen the signature is not inferred.

Am I missing something?

**Comment by pckilgore** [comment] 2020-06-01 04:29
I can't reproduce ( I added an id field but I doubt that did anything): 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/2559043/83375846-df4c5e00-a395-11ea-81b8-a55b123049ae.png">

I did notice that the typing isn't shown in vim until after the typegen file was generated, are you sure that was happening for you in a path the typescript compiler can see?

Here's my basic server snippet I have around for this: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/2559043/83375978-5c77d300-a396-11ea-92c0-99aace692a3a.png">

**Comment by otrebu** [comment] 2020-06-01 19:02
Interestingly it just started to work for me all of the sudden. Other people working on the same codebase didn't experience my problem. I am working on vscodium on Manjaro linux.
I don't even think we have updated the package.

**Comment by Weakky** [comment] 2020-10-12 14:31
Hey @otrebu,

There are two reasons you might have encountered this issue:

- Either TS did not pick up the typegen file, which sometimes happens. In this case, you generally simply need to open that file.
- Or you did not run your GraphQL server. Because @nexus/schema generates the typegen file at runtime, you need to make sure that your server is always running while working on it.

Closing now, feel free to reopen if you're still encountering it.

**Closed by Weakky** 2020-10-12 14:31 UTC

**Comment by Sytten** [comment] 2020-10-14 14:12
On the second point @Weakky I personally created structure where I can run `ts-node` and generate the typing without starting the server. I think documenting how to do that or creating a command for it would be nice.
